---
kind: pipeline
type: docker
name: default

steps:
- name: build docker image
  image: docker:latest
  volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  commands:
      - docker build -t go-sensors -f Dockerfile .

- name: get dependencies
  image: go-sensors
  commands:
  - go get

- name: build
  image: go-sensors
  commands:
  - go build

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock